import type { Course } from "../types";

/**
 * Every UVic course taken so far, across all 4 years. The 15 with real
 * coursework each got their own dedicated GitHub repo (labs, assignments, a
 * README documenting all of it, indexed together at
 * github.com/sahil-sanghvi/sahil-sanghvi-uvic) — those set `repo_url`.
 * Breadth/math/writing requirements, and courses still in progress with
 * nothing gradeable pushed yet, are listed with `repo_url: null`.
 */
export const courses: Course[] = [
  // ── Year 1 ──
  {
    id: "atwp-135",
    code: "ATWP 135",
    title: "Introduction to Academic Reading and Writing",
    term: "Fall 2023",
    year: 1,
    summary: "Writing requirement — no code.",
    repo_url: null,
  },
  {
    id: "writ-109",
    code: "WRIT 109",
    title: "Writer's World: Books + Film — Marvel",
    term: "Fall 2023",
    year: 1,
    summary: "Writing elective — no code.",
    repo_url: null,
  },
  {
    id: "math-100",
    code: "MATH 100",
    title: "Calculus I",
    term: "Fall 2023",
    year: 1,
    summary: "Math requirement — no code.",
    repo_url: null,
  },
  {
    id: "csc-110",
    code: "CSC 110",
    title: "Fundamentals of Programming I",
    term: "Fall 2023",
    year: 1,
    summary: "10 labs + 10 assignments in Python — variables through file I/O and an intro to classes.",
    repo_url: "https://github.com/sahil-sanghvi/fundamentals-of-programming-1",
  },
  {
    id: "math-101",
    code: "MATH 101",
    title: "Calculus II",
    term: "Spring 2024",
    year: 1,
    summary: "Math requirement — no code.",
    repo_url: null,
  },
  {
    id: "math-122",
    code: "MATH 122",
    title: "Logic and Foundations",
    term: "Spring 2024",
    year: 1,
    summary: "Math requirement — no code.",
    repo_url: null,
  },
  {
    id: "csc-115",
    code: "CSC 115",
    title: "Fundamentals of Programming II",
    term: "Spring 2024",
    year: 1,
    summary: "6 labs + 9 assignments in Java — ADTs from linked lists through BSTs, hash maps, and heaps.",
    repo_url: "https://github.com/sahil-sanghvi/fundamentals-of-programming-2",
  },
  {
    id: "csc-130",
    code: "CSC 130",
    title: "World Wide Web and Mobile Applications",
    term: "Spring 2024",
    year: 1,
    summary: "2 projects + 4 labs in HTML/CSS/JavaScript.",
    repo_url: "https://github.com/sahil-sanghvi/world-wide-web-and-mobile-applications",
  },
  {
    id: "csc-106",
    code: "CSC 106",
    title: "The Practice of Computer Science",
    term: "Spring 2024",
    year: 1,
    summary: "A SQLite exercise over an Olympics database.",
    repo_url: "https://github.com/sahil-sanghvi/the-practice-of-computer-science",
  },
  {
    id: "stat-123",
    code: "STAT 123",
    title: "Data Science",
    term: "Spring 2024",
    year: 1,
    summary: "4 assignments + 10 labs in R Markdown — sampling, wrangling, hypothesis testing, regression.",
    repo_url: "https://github.com/sahil-sanghvi/data-science",
  },

  // ── Year 2 ──
  {
    id: "csc-225",
    code: "CSC 225",
    title: "Algorithms and Data Structures I",
    term: "Fall 2024",
    year: 2,
    summary: "Array matching and brute-force-vs-sorted pair finding, benchmarked at scale.",
    repo_url: "https://github.com/sahil-sanghvi/algorithms-and-data-structures-1",
  },
  {
    id: "engr-240",
    code: "ENGR 240",
    title: "Technical Writing",
    term: "Fall 2024",
    year: 2,
    summary: "Writing requirement — no code.",
    repo_url: null,
  },
  {
    id: "math-202",
    code: "MATH 202",
    title: "Intermediate Calculus for CSC and EOS",
    term: "Fall 2024",
    year: 2,
    summary: "Math requirement — no code.",
    repo_url: null,
  },
  {
    id: "stat-260",
    code: "STAT 260",
    title: "Introduction to Probability and Statistics I",
    term: "Fall 2024",
    year: 2,
    summary: "Math requirement — no code.",
    repo_url: null,
  },
  {
    id: "seng-265",
    code: "SENG 265",
    title: "Software Development Methods",
    term: "Fall 2024",
    year: 2,
    summary: "2 assignments + 2 labs — a dynamic-memory survey analyzer in C and a PyQt6 GUI lab. Assignments 3-4 became Medilink.",
    repo_url: "https://github.com/sahil-sanghvi/software-development-methods",
  },
  {
    id: "csc-226",
    code: "CSC 226",
    title: "Algorithms and Data Structures II",
    term: "Spring 2025",
    year: 2,
    summary: "An Edmonds-Karp max-flow solver for a flight/pilot assignment problem.",
    repo_url: "https://github.com/sahil-sanghvi/algorithms-and-data-structures-2",
  },
  {
    id: "csc-230",
    code: "CSC 230",
    title: "Introduction to Computer Architecture",
    term: "Spring 2025",
    year: 2,
    summary: "4 assignments on an ATmega2560 — AVR assembly and C, up to an interrupt-driven LCD clock.",
    repo_url: "https://github.com/sahil-sanghvi/introduction-to-computer-architecture",
  },
  {
    id: "math-211",
    code: "MATH 211",
    title: "Matrix Algebra I",
    term: "Spring 2025",
    year: 2,
    summary: "Math requirement — no code.",
    repo_url: null,
  },
  {
    id: "seng-275",
    code: "SENG 275",
    title: "Software Testing",
    term: "Spring 2025",
    year: 2,
    summary: "A JUnit 5 + property-based test suite against the open-source JPacman engine.",
    repo_url: "https://github.com/sahil-sanghvi/software-testing",
  },

  // ── Year 3 ──
  {
    id: "csc-361",
    code: "CSC 361",
    title: "Computer Communications and Networks",
    term: "Fall 2025",
    year: 3,
    summary: "Raw-socket HTTP client, TCP analyzer, and traceroute reconstructor in Python.",
    repo_url: "https://github.com/sahil-sanghvi/computer-communications-and-networks",
  },
  {
    id: "csc-370",
    code: "CSC 370",
    title: "Database Systems",
    term: "Fall 2025",
    year: 3,
    summary: "Relational algebra and analytical SQL across two assignments.",
    repo_url: "https://github.com/sahil-sanghvi/database-systems",
  },
  {
    id: "seng-310",
    code: "SENG 310",
    title: "Human Computer Interaction",
    term: "Fall 2025",
    year: 3,
    summary: "Built Palendar, a calendar app, for this course — shipped as its own project rather than a coursework repo.",
    repo_url: null,
  },
  {
    id: "seng-321",
    code: "SENG 321",
    title: "Requirements Engineering",
    term: "Fall 2025",
    year: 3,
    summary: "No coursework artifacts kept.",
    repo_url: null,
  },
  {
    id: "csc-305",
    code: "CSC 305",
    title: "Introduction to Computer Graphics",
    term: "Summer 2025",
    year: 3,
    summary: "5 C++ renderers — 2D geometry through a BVH-accelerated ray tracer and a software rasterizer.",
    repo_url: "https://github.com/sahil-sanghvi/introduction-to-computer-graphics",
  },
  {
    id: "csc-330",
    code: "CSC 330",
    title: "Programming Languages",
    term: "Spring 2026",
    year: 3,
    summary: "5 assignments across OCaml, Racket, Ruby, and APL — functional sets, streams, a from-scratch interpreter, and DNA-sequence analysis.",
    repo_url: "https://github.com/sahil-sanghvi/programming-languages",
  },
  {
    id: "csc-360",
    code: "CSC 360",
    title: "Operating Systems",
    term: "Spring 2026",
    year: 3,
    summary: "A process manager, a pthreads concurrency sim, and a FAT12 filesystem toolkit, all in C.",
    repo_url: "https://github.com/sahil-sanghvi/operating-systems",
  },
  {
    id: "mech-150",
    code: "MECH 150",
    title: "3D Printing, Rapid Prototyping, and Design",
    term: "Spring 2026",
    year: 3,
    summary: "CAD models and print-ready files from a 3D design/printing breadth course.",
    repo_url: "https://github.com/sahil-sanghvi/3d-printing-rapid-prototyping-and-design",
  },
  {
    id: "csc-320",
    code: "CSC 320",
    title: "Foundations of Computer Science",
    term: "Spring 2026",
    year: 3,
    summary: "No coursework artifacts kept.",
    repo_url: null,
  },

  // ── Year 4 (in progress) ──
  {
    id: "csc-321",
    code: "CSC 321",
    title: "Introduction to Artificial Intelligence",
    term: "Fall 2026",
    year: 4,
    summary: "In progress — no assignments published yet.",
    repo_url: null,
  },
  {
    id: "csc-466",
    code: "CSC 466",
    title: "Overlay and Peer-to-Peer Networking",
    term: "Fall 2026",
    year: 4,
    summary: "In progress — no assignments published yet.",
    repo_url: null,
  },
  {
    id: "csc-485a",
    code: "CSC 485A",
    title: "Topics in Systems: GPU Computing",
    term: "Fall 2026",
    year: 4,
    summary: "In progress — no assignments published yet.",
    repo_url: null,
  },
  {
    id: "seng-365",
    code: "SENG 365",
    title: "Software Systems Development",
    term: "Fall 2026",
    year: 4,
    summary: "In progress — a multi-milestone software project, not yet published.",
    repo_url: null,
  },
  {
    id: "seng-474",
    code: "SENG 474",
    title: "Data Mining",
    term: "Fall 2026",
    year: 4,
    summary: "In progress — group project, not yet published.",
    repo_url: null,
  },
];
